name: CI/CD Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Run SQL Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: companydb
        run: |
          python -c "
import mysql.connector
from mysql.connector import Error

db_config = {
    'host': '${{ env.DB_HOST }}',
    'port': 3306,
    'user': '${{ env.DB_USER }}',
    'password': '${{ env.DB_PASSWORD }}',
    'database': '${{ env.DB_NAME }}'
}

try:
    connection = mysql.connector.connect(**db_config)
    cursor = connection.cursor()

    with open('add_departments.sql', 'r') as file:
        sql_script = file.read()

    statements = sql_script.strip().split(';')

    for stmt in statements:
        stmt = stmt.strip()
        if stmt:
            cursor.execute(stmt)
            print(f'Executed: {stmt}')

    connection.commit()
    print('All changes committed successfully.')

except Error as e:
    print(f'Error: {e}')

finally:
    try:
        if connection.is_connected():
            cursor.close()
            connection.close()
            print('MySQL connection closed.')
    except NameError:
        print('Connection was never established — check error above.')
"
